# Generated by Django 4.0.3 on 2022-03-25 09:33

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', cpf_field.models.CPFField(max_length=14, verbose_name='CPF')),
                ('aluguel', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor do aluguel')),
                ('tamanho', models.CharField(choices=[('P', 'PEQUENA'), ('M', 'MEDIA'), ('G', 'GRANDE')], max_length=1, verbose_name='Tamanho da kitnet')),
                ('status', models.BooleanField(verbose_name='Está inadimplente?')),
                ('atraso', models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Quanto tempo de inadimplencia?(em meses)')),
            ],
        ),
        migrations.DeleteModel(
            name='Cadastro',
        ),
    ]
