# Generated by Django 4.0.3 on 2022-03-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_registro_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='done',
            field=models.CharField(choices=[('doing', 'Doing'), ('done', 'Done')], default=1, max_length=12),
            preserve_default=False,
        ),
    ]
